### ISSUE TITLE
Support web

### ISSUE THREAD

**Issue by mbfakourii** [PuntitOwO/simple_pip_mode_flutter#14]
Can you support web?

JavaScript seems to support this feature
https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API

**Comment by PuntitOwO** [comment]
[Picture in Picture API](https://developer.mozilla.org/en-US/docs/Web/API/Picture-in-Picture_API) is only for video, and this is not the usecase of this plugin.
[Document Picture in Picture API](https://developer.mozilla.org/en-US/docs/Web/API/Document_Picture-in-Picture_API) is closer to the usecase, but it has limited browser compatibility as it seems.
I'm sorry.
