### ISSUE TITLE
Flutter application crash while using simple pip mode in release and debug mode while application is in background.

### ISSUE THREAD

**Issue by CodeRebirth** [PuntitOwO/simple_pip_mode_flutter#2]
Flutter application crash while using simple pip mode in release and debug mode while application is in background.

Here is the stack trace

kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
E/AndroidRuntime(11574): 	at cl.puntito.simple_pip_mode.SimplePipModePlugin.onDetachedFromActivity(SimplePipModePlugin.kt:87)
E/AndroidRuntime(11574): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnectionRegistry.java:392)
E/AndroidRuntime(11574): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:653)
E/AndroidRuntime(11574): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:676)
E/AndroidRuntime(11574): 	at android.app.Activity.performDestroy(Activity.java:7076)
E/AndroidRuntime(11574): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
E/AndroidRuntime(11574): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4292)
E/AndroidRuntime(11574): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4323)
E/AndroidRuntime(11574): 	at android.app.ActivityThread.-wrap6(ActivityThread.java)
E/AndroidRuntime(11574): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612)
E/AndroidRuntime(11574): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11574): 	at android.os.Looper.loop(Looper.java:163)
E/AndroidRuntime(11574): 	at android.app.ActivityThread.main(ActivityThread.java:6361)
E/AndroidRuntime(11574): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11574): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(11574): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
5
W/JavaBinder(11574): BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.google.android.play.core.internal.ai

**Comment by PuntitOwO** [comment]
@CodeRebirth Should be fixed now in v0.7.0
Reopen the issue if you still get this error.
