### ISSUE TITLE
Not working on ios

### ISSUE THREAD

**Issue by glennmichaelmejias** [PuntitOwO/simple_pip_mode_flutter#3]
Please add support for ios. Is it possible?

**Comment by mhdaslam790** [comment]
it is not possible

**Comment by glennmichaelmejias** [comment]
why?

**Comment by PuntitOwO** [comment]
I don't have an iOS device to develop and test so it's not possible for me to try that.
Any contribution, help or suggestion is appreciated!

**Comment by timleg002** [comment]
It seems that iOS can only officially do PiP for video playing, so a general PiP mode for iOS is quite impossible.

**Comment by PuntitOwO** [comment]
Thanks for clarifying @timleg002!
Closing the issue then, as this feature is not related to the package.

**Comment by mohd-afid** [comment]
Any ideas on how to do pip mode in iOS?

**Comment by timleg002** [comment]
> Any ideas on how to do pip mode in iOS? 
> 
> https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_for_video_calls
> There is one documentation that uses  Swift. 

The PiP mode in iOS is quite a bit different to Android. It seems to be limited only to video (whether playback or video calling..).
